Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Futebol.Models
{
    public class Jogador
    {
        public int ID { get; set; }
        public string NomeDoJogador { get; set; }
        public DateTime DataDeNascimento { get; set; }
        public string Nacionalidade { get; set; }
        public Posicao Posicao { get; set; } // Enum para posição
        public int CamisaNumero { get; set; }
        public float Altura { get; set; }
        public float Peso { get; set; }
        public PeDominante PeDominante { get; set; } // Enum para peDominante
        public int TimeID { get; set; }
        public Time Time { get; set; }
    }

    public enum Posicao
    {
        Goleiro,
        Zagueiro,
        Volante,
        Meia,
        Atacante,
        Lateral,
        Ala,
        Ponta,
        Técnico
    }

    public enum PeDominante
    {
        Direito,
        Esquerdo,
        Ambidestro
    }
}

Controllers/JogadorController.cs
using Futebol.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace Futebol.Controllers
{
    public class JogadorController : Controller
    {
        private FutebolDBContext db = new FutebolDBContext();

        // GET: Jogador
        public ActionResult Index(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            var jogadores = db.Jogadores.Include(j => j.Time); // Carrega os jogadores com seu relacionamento Time

            // Se o parâmetro de pesquisa for informado, aplica o filtro
            if (!String.IsNullOrEmpty(searchString))
            {
                jogadores = jogadores.Where(j => j.NomeDoJogador.Contains(searchString));
            }

            return View(jogadores.ToList()); // Retorna os jogadores (filtrados ou não)
        }

        // GET: Jogador/Details/id
        public ActionResult Details(int id)
        {
            var jogador = db.Jogadores
                .Include(j => j.Time) // Carrega explicitamente o Time relacionado
                .FirstOrDefault(j => j.ID == id);

            if (jogador == null)
            {
                return HttpNotFound();
            }

            return View(jogador);
        }

        // GET: Jogador/Create
        public ActionResult Create()
        {
            // Preenche a lista de times para o dropdown
            ViewBag.TimeID = new SelectList(db.Times, "ID", "NomeDoTime");
            // Preenche as opções do enum Posicao
            ViewBag.Posicoes = Enum.GetValues(typeof(Posicao)).Cast<Posicao>();
            // Preenche as opções do enum PeDominante
            ViewBag.PesDominantes = Enum.GetValues(typeof(PeDominante)).Cast<PeDominante>();

            return View();
        }

        // POST: Jogador/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Jogador jogador)
        {
            if (ModelState.IsValid)
            {
                db.Jogadores.Add(jogador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Preenche o dropdown novamente se ocorrer erro de validação
            ViewBag.TimeID = new SelectList(db.Times, "ID", "NomeDoTime", jogador.TimeID);
            ViewBag.Posicoes = Enum.GetValues(typeof(Posicao)).Cast<Posicao>();
            ViewBag.PesDominantes = Enum.GetValues(typeof(PeDominante)).Cast<PeDominante>();

            return View(jogador);
        }

        // GET: Jogador/Edit/id
        public ActionResult Edit(int id)
        {
            var jogador = db.Jogadores.Find(id);
            if (jogador == null)
            {
                return HttpNotFound();
            }

            // Preencher o ViewBag com a lista de times
            ViewBag.TimeID = new SelectList(db.Times, "ID", "NomeDoTime", jogador.TimeID);
            // Preenche as opções do enum Posicao
            ViewBag.Posicoes = Enum.GetValues(typeof(Posicao)).Cast<Posicao>();
            // Preenche as opções do enum PeDominante
            ViewBag.PesDominantes = Enum.GetValues(typeof(PeDominante)).Cast<PeDominante>();

            return View(jogador);
        }

        // POST: Jogador/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Jogador jogador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jogador).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Preenche o dropdown de times
            ViewBag.TimeID = new SelectList(db.Times, "ID", "NomeDoTime", jogador.TimeID);
            // Preenche as opções do enum Posicao
            ViewBag.Posicoes = Enum.GetValues(typeof(Posicao)).Cast<Posicao>();
            // Preenche as opções do enum PeDominante
            ViewBag.PesDominantes = Enum.GetValues(typeof(PeDominante)).Cast<PeDominante>();

            return View(jogador);
        }

        // GET: Jogador/Delete/id
        public ActionResult Delete(int id)
        {
            var jogador = db.Jogadores
                .Include(j => j.Time) // Carrega explicitamente o relacionamento com Time
                .FirstOrDefault(j => j.ID == id);

            if (jogador == null)
            {
                return HttpNotFound();
            }

            return View(jogador);
        }

        // POST: Jogador/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var jogador = db.Jogadores.Find(id);
            db.Jogadores.Remove(jogador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

Views/Jogador/Create.cshtml
@model Futebol.Models.Jogador

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Jogador</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.NomeDoJogador, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeDoJogador, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeDoJogador, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataDeNascimento, "Data de nascimento", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nacionalidade, "Nacionalidade", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Posicao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Posicao, new SelectList(ViewBag.Posicoes), "Selecione uma posição", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Posicao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CamisaNumero, "Número da Camisa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CamisaNumero, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CamisaNumero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Altura, "Altura", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Peso, "Peso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PeDominante, "Pé Dominante", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PeDominante, new SelectList(ViewBag.PesDominantes), "Selecione o pé dominante", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PeDominante, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TimeID, "TimeID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TimeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TimeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Jogador/Delete.cshtml
@model Futebol.Models.Jogador

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jogador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeDoJogador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDoJogador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CamisaNumero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CamisaNumero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Altura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Altura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeDominante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeDominante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time.NomeDoTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time.NomeDoTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Jogador/Details.cshtml
@model Futebol.Models.Jogador

@{
    ViewBag.Title = "Detalhes do Jogador";
}

<h2>Detalhes do Jogador</h2>

<div>
    <h4>Informações do Jogador</h4>
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.NomeDoJogador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CamisaNumero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CamisaNumero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Altura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Altura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeDominante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeDominante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time.NomeDoTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time.NomeDoTime)
        </dd>

    </dl>

    </dl>
</div>

<!-- Botões de navegação -->
<div class="mt-4">
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para a Lista", "Index", null, new { @class = "btn btn-secondary" })
</div>

Views/Jogador/Edit.cshtml
@model Futebol.Models.Jogador

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Jogador</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.NomeDoJogador, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeDoJogador, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeDoJogador, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nacionalidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Posicao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Posicao, new SelectList(ViewBag.Posicoes), "Selecione uma posição", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Posicao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CamisaNumero, "Número da Camisa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CamisaNumero, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CamisaNumero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PeDominante, "Pé Dominante", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PeDominante, new SelectList(ViewBag.PesDominantes), "Selecione o pé dominante", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PeDominante, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.TimeID, "TimeID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TimeID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TimeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Jogador/Index.cshtml
@model IEnumerable<Futebol.Models.Jogador>
@{ ViewBag.Title = "Index"; }
<h2>Listagem de Jogadores</h2>
<!-- Formulário de busca -->
@using (Html.BeginForm("Index", "Jogador", FormMethod.Get))
{
    <div class="form-group">
        <label for="searchString">Buscar jogador por nome:</label>
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Digite o nome do jogador" })
        <input type="submit" value="Pesquisar" class="btn btn-primary mt-2" />
    </div>}
<p>
    @Html.ActionLink("Criar Novo Jogador", "Create")
</p>
<!-- Tabela de jogadores -->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Time.NomeDoTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().NomeDoJogador)
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>@foreach (var item in Model)
    {
        <tr>
            <td>
            @Html.DisplayFor(modelItem => item.Time.NomeDoTime)
            </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeDoJogador)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.ID })
            @Html.ActionLink("Detalhes", "Details", new { id = item.ID })
            @Html.ActionLink("Excluir", "Delete", new { id = item.ID })
        </td>
        </tr>
    }
    </tbody>
</table>